services:
    jekyll-development:
        build: ./
        ports: 
            - 4000:4000
        volumes: 
            - ./:/srv/jekyll
        command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0" 